### ISSUE TITLE
I Have No Idea How To Open The ATF

### ISSUE THREAD

**Issue by PartTim3Hobo** [SonyWWS/ATF#35]
So long story short I downloaded the ZIP file and there is no application to install or run. I saw that most of the files were dependent on Visual Studio so I installed that but I have no idea what to do going forward. Any help would be appreciated.

**Comment by vorptronica** [comment]
If the download was successful, you should be able to open the samples solution file directly with Visual Studio's "Open Project" menu item.
Look for Samples.vs2010.sln inside the Samples folder. Load it into Visual Studio. And, despite the name "vs2010" on the file, you can open it in newer versions of Visual Studio than 2010.
This should give you a long list of projects to build and run from within Visual Studio showing off ATF in action. There are docs on those samples here: https://github.com/SonyWWS/ATF/wiki/ATF-Code-Samples
