### ISSUE TITLE
Syntax Editor license question

### ISSUE THREAD

**Issue by lxjk** [SonyWWS/ATF#47]
Hi there,

I noticed that ATF wrapped up Syntax Editor by ISyntaxEditorControl, and stated in  the comment about the license limit.
What exactly is the license limit regarding using the full functionality of Syntax Editor?
I'm currently looking to expose events like TriggerActivated, which is not included in ISyntaxEditorControl, is there a way to do it within the license limit?

Thank you!
Eric

**Comment by abeckus** [comment]
The   license doesn't allow us to expose full API.
Please see: ATF/ThirdParty/ActiPro/EULA Addendum for ATF.pdf  
However, you can buy a copy from
http://www.actiprosoftware.com/products/controls/windowsforms/syntaxeditor

Alan

**Comment by Ron2** [comment]
Hi Eric,

The license agreement between ATF and Actipro is in ATF's \ThirdParty\ActiPro directory, and is called "EULA Addendum for ATF.pdf". We/you are allowed to expose up to half of the API of SyntaxEditor. We developers interpreted this limitation by counting the number of members of SyntaxEditor and making sure that we did not expose more than 50% of them. As I recall, we were safely under the limit. (I no longer work at Sony, so I can't look up old emails about our analysis.)

Hope that helps.

--Ron
