### ISSUE TITLE
<xs:all> nodes ignored by DomGen.exe

### ISSUE THREAD

**Issue by JelleVM** [SonyWWS/ATF#52]
Hi there, 

Not quite sure how to create a pull request so just creating this as an issue. 

The DomGem.exe tool currently doesn't actually do anything <xs:all> nodes in a schema, it just ignores them. I added a change to XmlSchemaTypeLoader.cs to fix this.

XmlSchemaTypeLoader.cs, line 797, insert:

    // Check for <xs:all> node and continue processing it:
    XmlSchemaAll allNode = particle as XmlSchemaAll;
    if (allNode != null)
    {
        foreach (XmlSchemaElement elementInAll in allNode.Items)
            WalkParticle(elementInAll, nodeType);
    }
    else
    {
    ... the old parsing the XmlSchemaSequence etcetera...
    }

That should fix it. :-)  

Best,
Jelle

**Comment by abeckus** [comment]
Thanks for finding out the issue and posting a fix.
I make the suggested change in the next update.

Alan

**Comment by abeckus** [comment]
Fixed
Thanks for reporting the bug.

Thanks
Alan
