### ISSUE TITLE
element minOccurs and maxOccurs are ignored by 

### ISSUE THREAD

**Issue by JelleVM** [SonyWWS/ATF#60]
Consider the scenario where a third party XML file is read (using XmlSchemaLoader.cs) according to some XSD file that has been generated turned into a DOM structure. The AttributeInfo constructed for the elements will be of type `XmlAttributeInfo`. Some of these elements may have a minOccurs/maxOccurs set on them. This information is not preserved (i.e. it is for ChildNodes but not for elements).
When writing this XML again (using DomXmlWriter), this then results in problems where element nodes may not be written even though minOccurs was 1.

I think there are two potential fixes: either add these two properties to the `XmlAttributeInfo` class, or adding an AttributeCountRule and adding this to the info, in much the same way as there is the ChildCountRule. And then in DomXmlWriter.ShouldWriteAttribute check if minOccurs greater than 1.

Thanks!

**Comment by abeckus** [comment]
Thanks for reporting this issue.
The fixes look reasonable. I will have a fix for next ATF update.
please keep this issue open until it is fixed.

Alan

**Comment by abeckus** [comment]
Fixed,
Thanks for reporting the issue.

Alan
