### ISSUE TITLE
Redirect PropertyGrid data

### ISSUE THREAD

**Issue by nrvllrgrs** [SonyWWS/ATF#63]
Is there a way to redirect the contents of the property grid to a different node? I have a tree editor and a graph editor. Each tree node has an associated graph node. When the user selects the graph node, I would like the property grid to be updated as if the tree node were selected (but not actually select the tree node).

**Comment by abeckus** [comment]
one way is to implement IPropertyEditingContext.
for reference look at class SelectionPropertyEditingContext

Alan

**Comment by nrvllrgrs** [comment]
Do you have any more specifics? I'm looking but am not understanding.

**Comment by abeckus** [comment]
You need to understand  the implementation of the IPropertyEditingContext.
Look for all the IPropertyEditingContext implementation and see how it is being used.
Property editing in ATF is bit complex so it requires more effort to understand it comparing to other parts of ATF.

Good luck.
Alan
